/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class WordGame {

  ArrayList<String> words = new ArrayList<String>();
  ArrayList<Character> guesses = new ArrayList<Character>();
  String chosenWord;
  String renderedWord;
  static Integer attempts = 10;

  public void chooseWord() {
    Random random = new Random();
    Integer randomIndex = random.nextInt(words.size());
    chosenWord = words.get(randomIndex).toLowerCase();
    guesses.add(chosenWord.charAt(0));
  }

  public ArrayList<String> getWords() {
    return words;
  }

  public void buildWord() {
    char[] chosenWordArray = chosenWord.toCharArray();
    StringBuilder sb = new StringBuilder();

    for (Character ch : chosenWordArray) {
      if (guesses.contains(ch)) {
        sb.append(ch);
      } else {
        sb.append('_');
      }
    }
    renderedWord = sb.toString();
  }

  public void addWord(String word) {
    words.add(word);
  }

  public void addGuess(Character guess) {
    guesses.add(Character.toLowerCase(guess));
  }

  public Boolean checkWin() {
    return !renderedWord.contains("_");
  }

  // GETTERS
  public String getChosenWord() {
    return chosenWord;
  }

  public Integer getAttempts() {
    return attempts;
  }

  public ArrayList<Character> getGuesses() {
    return guesses;
  }

  public String getRenderedWord() {
    return renderedWord;
  }

  public static void main(String[] args) {
    WordGame game = new WordGame();
    Scanner scanner = new Scanner(System.in);

    game.addWord("Python");
    game.addWord("Java");
    game.addWord("Ruby");
    game.addWord("ActionScript");
    game.chooseWord();
    game.buildWord();
    System.out.println(game.getRenderedWord());

    for (Integer i = 1; i <= attempts; i++) {
      System.out.println("Give me a letter: ");
      game.addGuess(scanner.nextLine().toCharArray()[0]);
      game.buildWord();
      System.out.println(game.getRenderedWord());
      if (game.checkWin()) {
        System.out.println("You Won!");
        break;
      } else if (!game.checkWin() && i == attempts) {
        System.out.println("You Lost!");
      }
    }
    scanner.close();
  }
}
